-- Jazztikot June 2026 events
-- Venue: Jazztikot, Biela 5, Bratislava
-- Photos rotate: https://cjljktituvuamjwksuxg.supabase.co/storage/v1/object/public/event-covers/jazztikot/{1-5}.jpg

INSERT INTO events (title, category, date, time, duration, venue, city, lat, lng, is_free, cover_url, source, status, going_count, description)
VALUES
  ('Jazztikot | Jam session 21/26 – Juraj Kalasz a hostia', 'Music & Nightlife', '2026-06-02', '19:30', 3, 'Jazztikot, Biela 5', 'Bratislava', 48.1440, 17.1065, true, 'https://cjljktituvuamjwksuxg.supabase.co/storage/v1/object/public/event-covers/jazztikot/1.jpg', 'woeva_picks', 'published', 0, 'Pravidelná jam session pod vedením Juraja Kalasza a hostí. Živá hudba, jazz, blues a dobrá nálada v kultovom bratislavskom klube Jazztikot.'),
  ('Jazztikot | Katy Bertok Trio', 'Music & Nightlife', '2026-06-03', '19:30', 3, 'Jazztikot, Biela 5', 'Bratislava', 48.1440, 17.1065, true, 'https://cjljktituvuamjwksuxg.supabase.co/storage/v1/object/public/event-covers/jazztikot/2.jpg', 'woeva_picks', 'published', 0, 'Katy Bertok Trio vystúpi v Jazztikote s výberom z jazzového repertoáru. Večer plný emócií a živej hudby v srdci Bratislavy.'),
  ('Jazztikot | Tango večer Ivana Ecetová', 'Music & Nightlife', '2026-06-04', '19:30', 3, 'Jazztikot, Biela 5', 'Bratislava', 48.1440, 17.1065, true, 'https://cjljktituvuamjwksuxg.supabase.co/storage/v1/object/public/event-covers/jazztikot/3.jpg', 'woeva_picks', 'published', 0, 'Tango večer s Ivanou Ecetovou. Romantická atmosféra, vášnivá hudba a nezabudnuteľný večer v Jazztikote.'),
  ('Jazztikot | FOA feat. Gabo Jonas & Ivan Kormanak', 'Music & Nightlife', '2026-06-05', '19:30', 3, 'Jazztikot, Biela 5', 'Bratislava', 48.1440, 17.1065, true, 'https://cjljktituvuamjwksuxg.supabase.co/storage/v1/object/public/event-covers/jazztikot/4.jpg', 'woeva_picks', 'published', 0, 'FOA feat. Gabo Jonas & Ivan Kormanak – fusion jazz a autorská hudba v podaní skvelých slovenských muzikantov.'),
  ('Jazztikot | Memories Trio (F)', 'Music & Nightlife', '2026-06-06', '19:30', 3, 'Jazztikot, Biela 5', 'Bratislava', 48.1440, 17.1065, true, 'https://cjljktituvuamjwksuxg.supabase.co/storage/v1/object/public/event-covers/jazztikot/5.jpg', 'woeva_picks', 'published', 0, 'Memories Trio z Francúzska prináša jedinečný pohľad na jazz a world music. Medzinárodná hudba v srdci Bratislavy.'),
  ('Jazztikot | Jam session 22/26 – Juraj Kalasz a hostia', 'Music & Nightlife', '2026-06-09', '19:30', 3, 'Jazztikot, Biela 5', 'Bratislava', 48.1440, 17.1065, true, 'https://cjljktituvuamjwksuxg.supabase.co/storage/v1/object/public/event-covers/jazztikot/1.jpg', 'woeva_picks', 'published', 0, 'Pravidelná jam session pod vedením Juraja Kalasza a hostí. Živá hudba, jazz, blues a dobrá nálada v kultovom bratislavskom klube Jazztikot.'),
  ('Jazztikot | La Jana & Her Cats', 'Music & Nightlife', '2026-06-10', '19:30', 3, 'Jazztikot, Biela 5', 'Bratislava', 48.1440, 17.1065, true, 'https://cjljktituvuamjwksuxg.supabase.co/storage/v1/object/public/event-covers/jazztikot/2.jpg', 'woeva_picks', 'published', 0, 'La Jana & Her Cats – swing a jazz v tom najlepšom vydaní. Energický večer plný rytmu a tanca.'),
  ('Jazztikot | Sitracoustic', 'Music & Nightlife', '2026-06-11', '19:30', 3, 'Jazztikot, Biela 5', 'Bratislava', 48.1440, 17.1065, true, 'https://cjljktituvuamjwksuxg.supabase.co/storage/v1/object/public/event-covers/jazztikot/3.jpg', 'woeva_picks', 'published', 0, 'Sitracoustic – akustický večer plný atmosféry a originálnej hudby. Príjemný podvečer v Jazztikote.'),
  ('Jazztikot | Katarina Feldekova Band', 'Music & Nightlife', '2026-06-12', '19:30', 3, 'Jazztikot, Biela 5', 'Bratislava', 48.1440, 17.1065, true, 'https://cjljktituvuamjwksuxg.supabase.co/storage/v1/object/public/event-covers/jazztikot/4.jpg', 'woeva_picks', 'published', 0, 'Katarina Feldekova Band – inšpirujúce vokálne prevedenie jazzových štandardov a autorských skladieb.'),
  ('Jazztikot | Swingless Jazz Ensemble', 'Music & Nightlife', '2026-06-13', '19:30', 3, 'Jazztikot, Biela 5', 'Bratislava', 48.1440, 17.1065, true, 'https://cjljktituvuamjwksuxg.supabase.co/storage/v1/object/public/event-covers/jazztikot/5.jpg', 'woeva_picks', 'published', 0, 'Swingless Jazz Ensemble – moderný pohľad na jazz bez hraníc. Večer plný improvizácie a energie.'),
  ('Jazztikot | Jam session 23/26 – Juraj Kalasz a hostia', 'Music & Nightlife', '2026-06-16', '19:30', 3, 'Jazztikot, Biela 5', 'Bratislava', 48.1440, 17.1065, true, 'https://cjljktituvuamjwksuxg.supabase.co/storage/v1/object/public/event-covers/jazztikot/1.jpg', 'woeva_picks', 'published', 0, 'Pravidelná jam session pod vedením Juraja Kalasza a hostí. Živá hudba, jazz, blues a dobrá nálada v kultovom bratislavskom klube Jazztikot.'),
  ('Jazztikot | Korenova zelenina', 'Music & Nightlife', '2026-06-17', '19:30', 3, 'Jazztikot, Biela 5', 'Bratislava', 48.1440, 17.1065, true, 'https://cjljktituvuamjwksuxg.supabase.co/storage/v1/object/public/event-covers/jazztikot/2.jpg', 'woeva_picks', 'published', 0, 'Korenova zelenina – originálna slovenská kapela s neopakovateľným zvukom. Večer plný skvelej hudby v Jazztikote.'),
  ('Jazztikot | Silvia Josifoska & Ondrej Krajnak', 'Music & Nightlife', '2026-06-18', '19:30', 3, 'Jazztikot, Biela 5', 'Bratislava', 48.1440, 17.1065, true, 'https://cjljktituvuamjwksuxg.supabase.co/storage/v1/object/public/event-covers/jazztikot/3.jpg', 'woeva_picks', 'published', 0, 'Silvia Josifoska & Ondrej Krajnak – duo večer s krásnym vokálom a klavírom. Intímna atmosféra a živá hudba.'),
  ('Jazztikot | Nitraditional', 'Music & Nightlife', '2026-06-19', '19:30', 3, 'Jazztikot, Biela 5', 'Bratislava', 48.1440, 17.1065, true, 'https://cjljktituvuamjwksuxg.supabase.co/storage/v1/object/public/event-covers/jazztikot/4.jpg', 'woeva_picks', 'published', 0, 'Nitraditional – kapela z Nitry prináša fusion tradičnej a modernej hudby. Energický večer v Jazztikote.'),
  ('Jazztikot | Sabrina & Her Jazzin'' Spirit', 'Music & Nightlife', '2026-06-20', '19:30', 3, 'Jazztikot, Biela 5', 'Bratislava', 48.1440, 17.1065, true, 'https://cjljktituvuamjwksuxg.supabase.co/storage/v1/object/public/event-covers/jazztikot/5.jpg', 'woeva_picks', 'published', 0, 'Sabrina & Her Jazzin'' Spirit – vokálny jazz v podaní charizmatickej speváčky a jej skvelého bandu.'),
  ('Jazztikot | Jam session 24/26 – Juraj Kalasz a hostia', 'Music & Nightlife', '2026-06-23', '19:30', 3, 'Jazztikot, Biela 5', 'Bratislava', 48.1440, 17.1065, true, 'https://cjljktituvuamjwksuxg.supabase.co/storage/v1/object/public/event-covers/jazztikot/1.jpg', 'woeva_picks', 'published', 0, 'Pravidelná jam session pod vedením Juraja Kalasza a hostí. Živá hudba, jazz, blues a dobrá nálada v kultovom bratislavskom klube Jazztikot.'),
  ('Jazztikot | Sitra Achra', 'Music & Nightlife', '2026-06-24', '19:30', 3, 'Jazztikot, Biela 5', 'Bratislava', 48.1440, 17.1065, true, 'https://cjljktituvuamjwksuxg.supabase.co/storage/v1/object/public/event-covers/jazztikot/2.jpg', 'woeva_picks', 'published', 0, 'Sitra Achra – experimentálny jazz a improvizácia na hranici žánrov. Netradičný a inšpiratívny večer.'),
  ('Jazztikot | Blues Jam session Juraja Schweigerta', 'Music & Nightlife', '2026-06-25', '19:30', 3, 'Jazztikot, Biela 5', 'Bratislava', 48.1440, 17.1065, true, 'https://cjljktituvuamjwksuxg.supabase.co/storage/v1/object/public/event-covers/jazztikot/3.jpg', 'woeva_picks', 'published', 0, 'Blues Jam session Juraja Schweigerta – blues v najčistejšom vydaní. Večer plný duše a gitarového zvuku.'),
  ('Jazztikot | Dorota Nvotova – Slagrovna', 'Music & Nightlife', '2026-06-26', '19:30', 3, 'Jazztikot, Biela 5', 'Bratislava', 48.1440, 17.1065, true, 'https://cjljktituvuamjwksuxg.supabase.co/storage/v1/object/public/event-covers/jazztikot/4.jpg', 'woeva_picks', 'published', 0, 'Dorota Nvotova – Šlágrovna: šansóny, šlágre a poézia v podaní jednej z najvýraznejších slovenských speváčok.'),
  ('Jazztikot | Brono Dobrota Blues Rules', 'Music & Nightlife', '2026-06-27', '19:30', 3, 'Jazztikot, Biela 5', 'Bratislava', 48.1440, 17.1065, true, 'https://cjljktituvuamjwksuxg.supabase.co/storage/v1/object/public/event-covers/jazztikot/5.jpg', 'woeva_picks', 'published', 0, 'Brono Dobrota Blues Rules – blues rock večer s jedným z najlepších slovenských bluesmenov.'),
  ('Jazztikot | Jam session 25/26 – Juraj Kalasz a hostia', 'Music & Nightlife', '2026-06-30', '19:30', 3, 'Jazztikot, Biela 5', 'Bratislava', 48.1440, 17.1065, true, 'https://cjljktituvuamjwksuxg.supabase.co/storage/v1/object/public/event-covers/jazztikot/1.jpg', 'woeva_picks', 'published', 0, 'Pravidelná jam session pod vedením Juraja Kalasza a hostí. Živá hudba, jazz, blues a dobrá nálada v kultovom bratislavskom klube Jazztikot.');
